### ISSUE TITLE
Use C repr for fixed width types

### ISSUE THREAD

**Issue by jean-airoldie** [MaterializeInc/rust-dec#54]
Would you consider adding `#[repr(C)]` to the fixed width decimal types so they can be safely cast to and from bytes?

I know the `::from_le_bytes` & `::to_le_bytes` methods are available for that purpose, but when casting bytes into a decimal slice, its not possible to use such methods.

**Comment by sploiselle** [comment]
Can you instead use [`chunks`](https://doc.rust-lang.org/std/primitive.slice.html#method.chunks) on your bytes to convert it to a `Vec<Decimal128/64/etc>`?

```rust
#[test]
fn test_byte_deconstruction_reconstruction() -> Result<(), Box<dyn Error>> {
    let i = vec!["1", "100.1", "100.001"];
    let mut check_in = vec![];
    let mut buf = vec![];
    let mut cx = Context::<Decimal128>::default();

    for i in i {
        let d = cx.parse(i).unwrap();
        check_in.push(d.clone());
        buf.extend(d.to_le_bytes());
    }

    // Now `buf` is a bunch of bytes representing our Vec<Decimal128>`; we can
    // allocate a cut-to-length vec.
    let mut check_out = Vec::with_capacity(buf.len() / 16);

    for b in buf.chunks(16) {
        let d = Decimal128::from_le_bytes(b.try_into().expect("len 16"));
        check_out.push(d);
    }

    assert_eq!(check_in, check_out);
    Ok(())
}

**Comment by jean-airoldie** [comment]
Too slow basically. I want to cast a bigass trusted byte slice into a `&[Decimal64]` directly, without having to allocate or iterate etc.

Isn't the underlying `Decimal64` etc. already `repr(C)` anyway?

**Comment by jean-airoldie** [comment]
Using `#[repr(transparent)]` would also work to be clear.

**Comment by benesch** [comment]
(Recording a conversation from Slack with @sploiselle: `#[repr(transparent)]` SGTM.)
