### ISSUE TITLE
pow() doesn't work with floating point values

### ISSUE THREAD

**Issue by 772** [MaterializeInc/rust-dec#58]
4^2 = 16 works but 16^0.5 and 5^3.3 result in "NaN".

**Comment by benesch** [comment]
Hi @772, could you please provide a code sample demonstrating exactly how you're using the library? Thanks.

**Comment by 772** [comment]
Hello, here is my code:
```
use dec::Decimal;

fn main() {
	let mut a: Decimal::<200> = Decimal::from(16.0);
	let b: Decimal::<200> = Decimal::from(0.5);
	
	let mut ctx = dec::Context::<Decimal::<200>>::default();
	let _d = ctx.pow(&mut a, &b);
	
    println!("a^b = {}", a.to_string());
}

```

**Comment by benesch** [comment]
Ah, ok, it's because of these bits in the [upstream documentation](http://speleotrove.com/decimal/dnnumb.html):

> Some functions, such as decNumberExp, are described as mathematical functions. These have some restrictions: context.emax must be < 10^6, context.emin must be > –10^6, and context.digits must be < 10^6. Non-zero operands to these functions must also fit within these bounds.

> This is a mathematical function; the 10^6 restrictions on precision and range apply as described above, except that the normal range of values and context is allowed if the rhs has an integral value in the range –1999999997 through +999999999.

```rust
use dec::Decimal;

fn main() {
	let a: Decimal::<200> = Decimal::from(16.0);
	let b: Decimal::<200> = Decimal::from(0.5);
	let mut ctx = dec::Context::<Decimal::<200>>::default();
    ctx.set_min_exponent(-100).unwrap();
    ctx.set_max_exponent(100).unwrap();
    let mut res = a.clone();
	ctx.pow(&mut res, &b);
    println!("{} ^ {} = {}", a, b, res);
}

```

**Comment by 772** [comment]
Fantastic thanks. I guess that's all I need for my usecases.
