### ISSUE TITLE
Stacked borrows violation in `Context<Decimal<N>>::add`

### ISSUE THREAD

**Issue by icmccorm** [MaterializeInc/rust-dec#74]
I've been developing an experimental version of Miri that can execute foreign functions by interpreting LLVM bytecode. I was testing it on this crate, and it found a Stacked Borrows violation with `add` in `Context<Decimal<N>>`. This occurred when running the test case [test_cx_into_u64](https://github.com/MaterializeInc/rust-dec/blob/master/dec/tests/dec.rs#L1513), but a similar error occured for other test cases, too.
```
error: Undefined Behavior: attempting a read access using <151733> at alloc40166[0x8], but that tag does not exist in the borrow stack for this location
```
This is triggered by a read access on line 6378 of [decNumber.c](https://github.com/MaterializeInc/rust-dec/blob/master/decnumber-sys/decnumber/decNumber.c#L6378), in the function decUnitAddSub:

```
for (; c<minC; c++) {
    carry+=*a;
```
It seems like the error comes from how `lhs` is passed into the call to `decNumberAdd` on line 1439 of [decimal.rs](https://github.com/MaterializeInc/rust-dec/blob/master/dec/src/decimal.rs).

```
          decnumber_sys::decNumberAdd(
              lhs.as_mut_ptr(),
              lhs.as_ptr(),
              rhs.as_ptr(),
              &mut self.inner,
          );
```
I'm predicting that the first pointer to `lhs` mutated through before the second is read from, which would invalidate the read-only permission of the second pointer.

I've double-checked this using the new Tree Borrows semantics, and it produces a similar error at the same position:
```
error: Undefined Behavior: read access through <141372> is forbidden
```

**Comment by benesch** [comment]
Thanks for the heads up! I'm not going to have time to look into this, but perhaps @sploiselle does. 

Happy to entertain a PR, too, if it happens to be an easy fix. But I suspect it is somewhat complicated.
