### ISSUE TITLE
decNumber has potential memory unsafety

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/rust-dec#80]
As originally described in #75, there's potential memory unsafety in the underlying decNumber library. @icmccorm sent the report upstream to Mike Cowlishaw, but I wanted to have a placeholder tracking issue in this library. Ideally this would be fixed upstream, but if we don't hear back from Mike within a little bit, we could consider incorporating a patch here.

Details from #75:

> ...but it uncovered an out-of-bounds access in `test_overloading`:
> ```
> error: Undefined Behavior: memory access failed: alloc517857 has size 56, so pointer to 4 bytes starting at offset 54 is out-of-bounds
> ```
> This happens on line 2247 of `decBasic.c` during the `if` condition shown below:
> ```
> for (; *lo->msd==0 && lo->msd<lo->lsd;) lo->msd++;
> if (*lo->msd==0) {
>      ...
> }
> ```
> The value `0` is treated as a signed int, so the expression `*lo->msd` will read four bytes from this pointer. However, that may extend beyond the length of the allocation depending on how far the `
> for` loop increments `lo->msd`. 
> 
> There's also an issue with `test_standard_notation_decimal`. It seems like the counter is reading beyond the length of the struct into the uninitialized padding at the end. Consider the following for loop in `decNumberGetBCD`:
> ```
> uInt u=*up;                 
> uInt cut=DECDPUN;              
> for (; ub>=bcd; ub--) {
>      *ub=(uByte)(u%10);          
>      u=u/10;
>      cut--;
>      if (cut>0) continue;
>      up++;
>      u=*up; 
>      cut=DECDPUN;
> }
> ```
> On the final iteration, depending on the number of digits, the expression `u=*up;` may read beyond the end of the `up`.  This error occurs as a read of uninitialized memory since there's some padding at the end of the `decNumber` struct. When I add a conditional, all tests pass, but I'm unsure if this is the best approach to fix this
> ```
>      if (cut>0) continue;
>      up++;
>      if (ub - 1 >= bcd)
>           u=*up; 
> ```

**Comment by icmccorm** [comment]
I never received a response from Mike, but I've submitted two patches upstream to GCC that fix these issues. 

- [[PATCH 1/2] libdecnumber: fixed undefined behavior in `decFloatFMA`
](https://gcc.gnu.org/pipermail/gcc-patches/2024-February/644839.html)
- [[PATCH 2/2] libdecnumber: fixed undefined behavior in `decNumberGetBCD`](https://gcc.gnu.org/pipermail/gcc-patches/2024-February/644840.html)
 
Once these are merged, then all tests will pass in my custom version of Miri.

**Comment by benesch** [comment]
Ah, sorry you never heard back. Thanks for reaching out. If GCC is able to
review and merge the patches I’m happy to also merge them here, even if
they never make it up to libdecnumber proper.

**Comment by def-** [comment]
Since I also ran into this in https://github.com/MaterializeInc/materialize/issues/25634 I put up a fix: https://github.com/MaterializeInc/rust-dec/pull/81
